/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barreiralarrañaga.Interfaz;

import barreiralarrañaga.Dominio.MetodosControl;
import barreiralarrañaga.Dominio.Sistema;
import barreiralarrañaga.Dominio.Sorteo;

/**
 *
 * @author Juan
 */
public class NuevoSorteoUI extends javax.swing.JFrame {

    Sistema sis;

    /**
     * Creates new form NuevoSorteoUI
     */
    public NuevoSorteoUI(Sistema auxSist) {
        sis = auxSist;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFieldDescPremio = new javax.swing.JTextField();
        txtFieldCantidadGanadores = new javax.swing.JTextField();
        btnFieldCantidadGanadores = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Premio");

        jLabel2.setText("Numero de ganadores");

        txtFieldDescPremio.setText("jTextField1");

        txtFieldCantidadGanadores.setText("jTextField1");

        btnFieldCantidadGanadores.setText("jButton1");
        btnFieldCantidadGanadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldCantidadGanadoresActionPerformed(evt);
            }
        });

        btnCancelar.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(txtFieldDescPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFieldCantidadGanadores)
                                .addGap(70, 70, 70)
                                .addComponent(btnCancelar))
                            .addComponent(txtFieldCantidadGanadores, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldDescPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldCantidadGanadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFieldCantidadGanadores)
                    .addComponent(btnCancelar))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFieldCantidadGanadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldCantidadGanadoresActionPerformed
        MetodosControl m = new MetodosControl();
        if (m.validInt(txtFieldCantidadGanadores.getText())) {
            int cantGandores = Integer.parseInt(txtFieldCantidadGanadores.getText());
            if (!txtFieldDescPremio.getText().isEmpty() /*HAY QUE REVISAR QUE LA CANTIDAD DE GANADORES NO SEA MAYOR A LA DEPARTICIPANTES, O SI? */) {
                Sorteo sorteoActual = new Sorteo(txtFieldDescPremio.getText(), cantGandores);
                sis.setSorteoActual(sorteoActual);
    }//GEN-LAST:event_btnFieldCantidadGanadoresActionPerformed
            else{
            
            //PONER PANE DE ALERTA ERROR
            }
        
        }else{
        
       // PONER MENSAJE DE ERROR
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFieldCantidadGanadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFieldCantidadGanadores;
    private javax.swing.JTextField txtFieldDescPremio;
    // End of variables declaration//GEN-END:variables
}
