/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barreiralarrañaga.Interfaz;

import barreiralarrañaga.Dominio.Sistema;
import barreiralarrañaga.Dominio.Sorteo;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class NuevoSorteoUI extends javax.swing.JFrame {

    Sistema sis;

    /**
     * Creates new form NewSorteoUI
     */
    public NuevoSorteoUI(Sistema unSis) {
        initComponents();
        sis = unSis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGanadores = new javax.swing.JLabel();
        spinnerGanadores = new javax.swing.JSpinner();
        btnCrear = new javax.swing.JButton();
        LblNuevoSorteo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        txtNombreSorteo = new javax.swing.JTextField();
        txtFieldDescPremio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblGanadores.setText("Cantidad de Ganadores:");

        btnCrear.setText("Crear Sorteo");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        LblNuevoSorteo.setText("Nuevo Sorteo");

        lblNombre.setText("Nombre de sorteo:");

        lblDesc.setText("Descripcion de premio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblGanadores)
                                .addComponent(lblDesc)
                                .addComponent(lblNombre))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spinnerGanadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreSorteo)
                                .addComponent(txtFieldDescPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCrear)
                            .addGap(36, 36, 36)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(LblNuevoSorteo)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblNuevoSorteo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombreSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesc)
                    .addComponent(txtFieldDescPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGanadores)
                    .addComponent(spinnerGanadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        int valueSpinner = (Integer) spinnerGanadores.getValue();
        int resp = 0;
        if (!txtNombreSorteo.getText().isEmpty()) {
            if (valueSpinner > 0) {
                if (!txtFieldDescPremio.getText().isEmpty()) {

                    if (sis.getSorteoActual() != null) {
                        resp = JOptionPane.showConfirmDialog(this, "Esta seguro que quiere sobreescribir el sorteo actual?", "Sorteo en marcha", JOptionPane.YES_NO_OPTION);
                    }
                    if (resp == 0) {
                        Sorteo sorteoActual = new Sorteo(txtNombreSorteo.getText(), txtFieldDescPremio.getText(), valueSpinner);
                        sis.setSorteoActual(sorteoActual);
                        this.dispose();
                    } else if (resp == 1) {
                        this.dispose();
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Ingrese una descripcion para el premio", "Premio Invalido", JOptionPane.ERROR_MESSAGE);

                }

            } else {
                JOptionPane.showMessageDialog(this, "Se necesita al menos un ganador", "Cantidad de ganadores invalida", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para el sorteo", "Nombre Invalido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblNuevoSorteo;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblGanadores;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JSpinner spinnerGanadores;
    private javax.swing.JTextField txtFieldDescPremio;
    private javax.swing.JTextField txtNombreSorteo;
    // End of variables declaration//GEN-END:variables
}
