
package barreiralarrañaga.Interfaz;

import barreiralarrañaga.Dominio.Sistema;
import barreiralarrañaga.Dominio.Sorteo;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class NuevoSorteoUI extends javax.swing.JFrame {

    Sistema sis;

    /**
     * Creates new form NuevoSorteoUI
     */
    public NuevoSorteoUI(Sistema auxSist) {
        sis = auxSist;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFieldDescPremio = new javax.swing.JTextField();
        btnFieldCantidadGanadores = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        spinnerGanadores = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Premio");

        jLabel2.setText("Numero de ganadores");

        txtFieldDescPremio.setText("jTextField1");
        txtFieldDescPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDescPremioActionPerformed(evt);
            }
        });

        btnFieldCantidadGanadores.setText("jButton1");
        btnFieldCantidadGanadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldCantidadGanadoresActionPerformed(evt);
            }
        });

        btnCancelar.setText("jButton2");

        spinnerGanadores.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerGanadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFieldDescPremio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFieldCantidadGanadores)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldDescPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerGanadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFieldCantidadGanadores)
                    .addComponent(btnCancelar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFieldCantidadGanadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldCantidadGanadoresActionPerformed

        int valueSpinner = (Integer) spinnerGanadores.getValue();
        if (valueSpinner > 0) {
            if (!txtFieldDescPremio.getText().isEmpty() /*HAY QUE REVISAR QUE LA CANTIDAD DE GANADORES NO SEA MAYOR A LA DEPARTICIPANTES, O SI? */) {
                Sorteo sorteoActual = new Sorteo(txtFieldDescPremio.getText(), valueSpinner);
                sis.setSorteoActual(sorteoActual);

    }//GEN-LAST:event_btnFieldCantidadGanadoresActionPerformed
            else {
                JOptionPane.showMessageDialog(this, "Ingrese una descripcion para el premio", "Premio Invalido", JOptionPane.ERROR_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Se necesita al menos un ganador", "Cantidad de ganadores invalida", JOptionPane.ERROR_MESSAGE);

        }
    }
    private void txtFieldDescPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDescPremioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDescPremioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFieldCantidadGanadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spinnerGanadores;
    private javax.swing.JTextField txtFieldDescPremio;
    // End of variables declaration//GEN-END:variables
}
